spring:
  config:
    import: "application-secret.yml"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: i_see_you

  datasource:
    url: jdbc:mysql://localhost:3306/i_see_you?useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "A123456789a!"
    driver-class-name: com.mysql.cj.jdbc.Driver


  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
          jobStore:
            tablePrefix: quartz.QRTZ_
            isClustered: false
          threadPool:
            threadCount: 5


